### ISSUE TITLE
Use javascript based snappy compressor

### ISSUE THREAD

**Issue by pimpelsang** [tulios/kafkajs-snappy#1]
main point for using kafkaJS instead node c++ rdkafka, is because it doesn't depend on node gyp c++ compiling and bindings.

If you depend on c++ snappy then it still requires and much of the benefit is lost.

I've got it working with this lib, its 50% slower but it doesn't matter that much when messages are small and rare.
https://github.com/zhipeng-jia/snappyjs

**Comment by tulios** [comment]
Fixed by #2
