### ISSUE TITLE
[Performance] snappy vs snappyjs

### ISSUE THREAD

**Issue by valamidev** [tulios/kafkajs-snappy#4]
Hi,

while using `kafkajs-snappy` under load of  ~1000 message / sec (~600 byte / message), we just experienced that snappyjs give too much blocking and that result **up to 5x** higher latency than using the C++ based snappy package.

My suggestion to switch back to https://www.npmjs.com/package/snappy as it is much more fit for real world use cases, or at least leave a hint as a solution for better performance.

**Comment by pimpelsang** [comment]
I do agree with this with larger messages / loads. Maybe there should be choice. kafkajs-snappyjs and kafkajs-snappy packages?

**Comment by pimpelsang** [comment]
created https://www.npmjs.com/package/kafkajs-snappy-native
